settings:
  mappings-merge: true          # true = merge config entries into Java defaults (recommended), false = Only use the settings configured here
  enable-block-points: true     # enable awarding points for breaking configured blocks
  enable-mob-points: true       # enable awarding points for killing configured mobs
  ignore-silk-touch: false      # if true, then silk-touch won't block point awarding
  silk-touch-message: true      # if true it shows a message when silk-touch prevented points gained
  multiplier: 1.0               # global multiplier applied to all earned points
  action-bar-enabled: true      # show action bar updates
  update-interval-ticks: 1      # action bar and timer task interval in ticks
  save-interval-seconds: 300    # automatic save interval
  shutdown-on-end: true         # default
  end-top-count: 5              # how many top players to show at match end

timer:
  default-duration: "30m" # I dont think this works
  
# shows Points of users (UUID)
points: {} 

# override or add mob point values
mob-points:
  ZOMBIE: 2
  ZOMBIE_VILLAGER: 3
  HUSK: 3
  DROWNED: 3
  SKELETON: 3
  STRAY: 3
  SPIDER: 2
  CAVE_SPIDER: 4
  SILVERFISH: 2
  ENDERMITE: 4
  SLIME: 3
  PHANTOM: 5
  ZOMBIE_HORSE: 2
  SKELETON_HORSE: 2
  ZOMBIFIED_PIGLIN: 3
  CREEPER: 6
  ENDERMAN: 15
  BLAZE: 15
  MAGMA_CUBE: 8
  GUARDIAN: 12
  HOGLIN: 9
  ZOGLIN: 9
  PIGLIN: 2
  PILLAGER: 8
  VINDICATOR: 12
  EVOKER: 30
  VEX: 20
  RAVAGER: 35
  WITHER_SKELETON: 28
  GHAST: 20
  PIGLIN_BRUTE: 40
  SHULKER: 25
  ILLUSIONER: 25
  ELDER_GUARDIAN: 100
  WITHER: 250
  WARDEN: 375
  ENDER_DRAGON: 500

# override ore point values
block-points:
  COAL_ORE: 1
  DEEPSLATE_COAL_ORE: 1
  IRON_ORE: 2
  DEEPSLATE_IRON_ORE: 2
  COPPER_ORE: 2
  DEEPSLATE_COPPER_ORE: 2
  GOLD_ORE: 4
  DEEPSLATE_GOLD_ORE: 4
  REDSTONE_ORE: 2
  DEEPSLATE_REDSTONE_ORE: 2
  LAPIS_ORE: 3
  DEEPSLATE_LAPIS_ORE: 3
  DIAMOND_ORE: 12
  DEEPSLATE_DIAMOND_ORE: 12
  EMERALD_ORE: 12
  DEEPSLATE_EMERALD_ORE: 12
  NETHER_QUARTZ_ORE: 1
  NETHER_GOLD_ORE: 1
  ANCIENT_DEBRIS: 30

# End message
messages:
  prefix: "&7[&bPointHunt&7] &r"
  points-self: "&aYou have &e{points} &apoints." 
  hunt-ended-title: "§cTHE POINT HUNT HAS ENDED!"
