name: PointHunt
version: '1.0-SNAPSHOT'
main: me.micahcode.pointHunt.handlers.PointHunt
api-version: '1.21'
authors: [ MicahCode ]
description: PointHunt
website: https://micahcode.com/
commands:
  hunt:
    description: Main command for Rank Hunt
    usage: /hunt [top <page>|set <player> <points>|reset|reload]
    aliases: [rh]
    permission: pointhunt.use
    permission-message: "&cYou don't have permission to use that command."
permissions:
  pointhunt.use:
    description: Allows use of /hunt (basic commands, viewing)
    default: true
  pointhunt.setPoints:
    description: Allows setting points for a player.
    default: op
  pointhunt.resetPoints:
    description: Allows resetting the leaderboard.
    default: op
  pointhunt.setTimer:
    description: Allows setting/resuming the timer.
    default: op
  pointhunt.cancelTimer:
    description: cancels the timer
    default: op
  pointhunt.resumeTimer:
    description: resume the timer
    default: op
  pointhunt.admin.reload:
    description: Allows reloading the PointHunt configuration (reloads config and mappings)
    default: op